variables:
  IMAGE_NAME: kennedyuche/ubuntu-base
  IMAGE_TAG: v1
  APP_NAME: helm-app

stages:
  - deploy

connect_k8s:
  stage: deploy
  image: $IMAGE_NAME:$IMAGE_TAG
  before_script:
    - chmod +x helm-deploy.sh
  script:
    - . helm-deploy.sh