app:
  name: "udagram"

secret:
  access_key_id: "YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBWlVaVFVRV0VPTEhFNFVXVQphd3Nfc2VjcmV0X2FjY2Vz"
  secret_access_key: "c19rZXkgPSBNakxKSXRhUVlLc2pMWDJXS1VqYTlDSUtUUWdVRURLelJJWnZNMncwCg=="
  postgres_username: "dWRhZ3JhbV9wc3Fs"
  postgres_password: "cHNxbDE0NzA="

config:
  host: "udagram-db-dev.cwqsxxb7gfqx.us-east-1.rds.amazonaws.com"
  database: "postgres"
  bucket: "udagram-kennedy-bucket-3"
  region: "us-east-1"
  profile: "default"
  secret: "testing"
  end_point: "http://localhost:8100"

backend:
  replicas: "2"
  image: "kennedyuche/udagram-backend"
  tag: "latest"
  resources:
    requests:
      memory: "50Mi"
      cpu: "20m"
    limits:
      memory: ""
      cpu:

frontend:
  replicas: "1"
  image: "kennedyuche/udagram-frontend"
  tag: "latest"
  resources:
    requests:
      memory: "50Mi"
      cpu: "20m"
    limits:
      memory: ""
      cpu:

proxy:
  replicas: "1"
  image: "kennedyuche/udagram-reverseproxy"
  tag: "v1"
  resources:
    requests:
      memory: "50Mi"
      cpu: "20m"
    limits:
      memory: ""
      cpu: