apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-aws
type: Opaque
data:
  aws_access_key_id: {{ .Values.secret.access_key_id }}
  aws_secret_access_key: {{ .Values.secret.secret_access_key }}