apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.frontend.name }}
  name: {{ .Values.frontend.name }}
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: {{ .Values.frontend.name }}
  type: ClusterIP