apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.proxy.name }}
  name: {{ .Values.proxy.name }}
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: {{ .Values.proxy.name }}
  type: ClusterIP