apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-proxy
spec:
  selector:
    matchLabels:
      service: {{ .Values.app.name }}-proxy
  replicas: {{ .Values.proxy.replicas }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        service: {{ .Values.app.name }}-proxy
    spec:
      containers:
      - image: {{ .Values.proxy.image }}:{{ .Values.proxy.tag }}
        name: {{ .Values.app.name }}-proxy
        imagePullPolicy: Always
        resources:
          {{- if .Values.proxy.resources.requests }}
          requests:
            memory: {{ .Values.proxy.resources.requests.memory | default "64Mi" | quote }}
            cpu: {{ .Values.proxy.resources.requests.cpu | default "250m" | quote }}
          {{- else }}
          requests:
            memory: "64Mi"
            cpu: "250m"
          {{- end }}

          {{- if .Values.proxy.resources.limits }}
          limits:
            memory: {{ .Values.proxy.resources.limits.memory | default "1024Mi" | quote }}
            cpu: {{ .Values.proxy.resources.limits.cpu | default "500m" | quote }}
          {{- else }}
          limits:
            memory: "1024Mi"
            cpu: "500m"
          {{- end }}
        ports:
        - containerPort: 8080
      restartPolicy: Always