kind: Deployment
apiVersion: apps/v1
metadata:
 name: {{ .Values.app.name }}-backend
spec:
  selector:
    matchLabels:
      service: {{ .Values.app.name }}-backend
  replicas: {{ .Values.backend.replicas }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        service: {{ .Values.app.name }}-backend
    spec:
      containers:
      - image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
        name: {{ .Values.app.name }}-backend
        imagePullPolicy: Always
        resources:
          {{- if .Values.backend.resources.requests }}
          requests:
            memory: {{ .Values.backend.resources.requests.memory | default "100Mi" | quote }}
            cpu: {{ .Values.backend.resources.requests.cpu | default "10m" | quote }}
          {{- else }}
          requests:
            memory: "100Mi"
            cpu: "10m"
          {{- end }}

          {{- if .Values.backend.resources.limits }}
          limits:
            memory: {{ .Values.backend.resources.limits.memory | default "2048Mi" | quote }}
            cpu: {{ .Values.backend.resources.limits.cpu | default "500m" | quote }}
          {{- else }}
          limits:
            memory: "2048Mi"
            cpu: "500m"
          {{- end }}

        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-env
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-env
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-env
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-env
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-env
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-env
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-env
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-env
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-env
              key: POSTGRES_USERNAME
        volumeMounts:
        - name: {{ .Values.app.name }}-aws
          mountPath: "/root/.aws/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: {{ .Values.app.name }}-aws
        secret:
          secretName: {{ .Values.app.name }}-aws