apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.app.name }}-frontend
  name: {{ .Values.app.name }}-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: {{ .Values.app.name }}-frontend
  type: ClusterIP