apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.app.name }}-proxy
  name: {{ .Values.app.name }}-proxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: {{ .Values.app.name }}-proxy
  type: ClusterIP